#include "Object3dLoader.h"

namespace Utils {




int Object3dLoader::loadObject()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-30-687d9f57:1348a8da27a:-8000:0000000000000C7B begin
{
    return 0;
}
// section -64--88-1-30-687d9f57:1348a8da27a:-8000:0000000000000C7B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace Utils */
