#include "UrlLoader.h"

namespace Utils {




int UrlLoader::loadString(void  url)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-30--5502e962:1347fefb423:-8000:0000000000000C5D begin
{
    return 0;
}
// section -64--88-1-30--5502e962:1347fefb423:-8000:0000000000000C5D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace Utils */
