/* soapStub.h
   Generated by gSOAP 2.8.8 from Products.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#include <vector>
#define SOAP_NAMESPACE_OF_ns1	"urn:ProductsControllerwsdl"
#include "stdsoap2.h"
#if GSOAP_VERSION != 20808
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_ns1__Products
#define SOAP_TYPE_ns1__Products (10)
/* ns1:Products */
class SOAP_CMAC ns1__Products
{
public:
	std::string idProducts;	/* required element of type xsd:integer */
	std::string name;	/* required element of type xsd:string */
	float price;	/* required element of type xsd:float */
	std::string ref;	/* required element of type xsd:string */
	std::string description;	/* required element of type xsd:string */
	int idMarker;	/* required element of type xsd:int */
	std::string model3d;	/* required element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 10; } /* = unique id SOAP_TYPE_ns1__Products */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns1__Products() { ns1__Products::soap_default(NULL); }
	virtual ~ns1__Products() { }
};
#endif

#ifndef SOAP_TYPE_ns1__ProductImages
#define SOAP_TYPE_ns1__ProductImages (12)
/* ns1:ProductImages */
class SOAP_CMAC ns1__ProductImages
{
public:
	std::string idProductImage;	/* required element of type xsd:integer */
	std::string url;	/* required element of type xsd:string */
	std::string altName;	/* required element of type xsd:string */
	std::string idProduct;	/* required element of type xsd:integer */
	std::string owner;	/* required element of type xsd:integer */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 12; } /* = unique id SOAP_TYPE_ns1__ProductImages */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns1__ProductImages() { ns1__ProductImages::soap_default(NULL); }
	virtual ~ns1__ProductImages() { }
};
#endif

#ifndef SOAP_TYPE_ProductImagesArray
#define SOAP_TYPE_ProductImagesArray (11)
/* SOAP encoded array of ns1:ProductImages schema type: */
class SOAP_CMAC ProductImagesArray
{
public:
	ns1__ProductImages **__ptr;
	int __size;
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 11; } /* = unique id SOAP_TYPE_ProductImagesArray */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ProductImagesArray() { ProductImagesArray::soap_default(NULL); }
	virtual ~ProductImagesArray() { }
};
#endif

#ifndef SOAP_TYPE_ns1__getProductResponse
#define SOAP_TYPE_ns1__getProductResponse (17)
/* ns1:getProductResponse */
struct ns1__getProductResponse
{
public:
	ns1__Products *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:Products */
};
#endif

#ifndef SOAP_TYPE_ns1__getProduct
#define SOAP_TYPE_ns1__getProduct (21)
/* ns1:getProduct */
struct ns1__getProduct
{
public:
	int companyID;	/* required element of type xsd:int */
	std::string userMD5;	/* required element of type xsd:string */
	std::string product;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__getImagesDataResponse
#define SOAP_TYPE_ns1__getImagesDataResponse (22)
/* ns1:getImagesDataResponse */
struct ns1__getImagesDataResponse
{
public:
	ProductImagesArray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfProductImages */
};
#endif

#ifndef SOAP_TYPE_ns1__getImagesData
#define SOAP_TYPE_ns1__getImagesData (26)
/* ns1:getImagesData */
struct ns1__getImagesData
{
public:
	int companyID;	/* required element of type xsd:int */
	std::string userMD5;	/* required element of type xsd:string */
	std::string product;	/* required element of type xsd:string */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (27)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
private:
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (28)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (30)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (33)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (34)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE_xsd__integer
#define SOAP_TYPE_xsd__integer (9)
typedef std::string xsd__integer;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


#endif

/* End of soapStub.h */
