/* soapH.h
   Generated by gSOAP 2.8.8 from Products.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_float
#define SOAP_TYPE_float (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_float(struct soap*, float *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_float(struct soap*, const char*, int, const float *, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_in_float(struct soap*, const char*, float *, const char*);

#ifndef soap_write_float
#define soap_write_float(soap, data) ( soap_begin_send(soap) || soap_put_float(soap, data, "float", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_float(struct soap*, const float *, const char*, const char*);

#ifndef soap_read_float
#define soap_read_float(soap, data) ( soap_begin_recv(soap) || !soap_get_float(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 float * SOAP_FMAC4 soap_get_float(struct soap*, float *, const char*, const char*);

#ifndef SOAP_TYPE_ns1__ProductImages
#define SOAP_TYPE_ns1__ProductImages (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ProductImages(struct soap*, const char*, int, const ns1__ProductImages *, const char*);
SOAP_FMAC3 ns1__ProductImages * SOAP_FMAC4 soap_in_ns1__ProductImages(struct soap*, const char*, ns1__ProductImages *, const char*);

#ifndef soap_write_ns1__ProductImages
#define soap_write_ns1__ProductImages(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:ProductImages", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read_ns1__ProductImages
#define soap_read_ns1__ProductImages(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ProductImages(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns1__ProductImages * SOAP_FMAC4 soap_get_ns1__ProductImages(struct soap*, ns1__ProductImages *, const char*, const char*);

#define soap_new_ns1__ProductImages(soap, n) soap_instantiate_ns1__ProductImages(soap, n, NULL, NULL, NULL)


#define soap_delete_ns1__ProductImages(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns1__ProductImages * SOAP_FMAC2 soap_instantiate_ns1__ProductImages(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ProductImages(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ProductImagesArray
#define SOAP_TYPE_ProductImagesArray (11)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ProductImagesArray(struct soap*, const char*, int, const ProductImagesArray *, const char*);
SOAP_FMAC3 ProductImagesArray * SOAP_FMAC4 soap_in_ProductImagesArray(struct soap*, const char*, ProductImagesArray *, const char*);

#ifndef soap_write_ProductImagesArray
#define soap_write_ProductImagesArray(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "SOAP-ENC:Array", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read_ProductImagesArray
#define soap_read_ProductImagesArray(soap, data) ( soap_begin_recv(soap) || !soap_get_ProductImagesArray(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ProductImagesArray * SOAP_FMAC4 soap_get_ProductImagesArray(struct soap*, ProductImagesArray *, const char*, const char*);

#define soap_new_ProductImagesArray(soap, n) soap_instantiate_ProductImagesArray(soap, n, NULL, NULL, NULL)


#define soap_delete_ProductImagesArray(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ProductImagesArray * SOAP_FMAC2 soap_instantiate_ProductImagesArray(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ProductImagesArray(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__Products
#define SOAP_TYPE_ns1__Products (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__Products(struct soap*, const char*, int, const ns1__Products *, const char*);
SOAP_FMAC3 ns1__Products * SOAP_FMAC4 soap_in_ns1__Products(struct soap*, const char*, ns1__Products *, const char*);

#ifndef soap_write_ns1__Products
#define soap_write_ns1__Products(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:Products", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read_ns1__Products
#define soap_read_ns1__Products(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__Products(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns1__Products * SOAP_FMAC4 soap_get_ns1__Products(struct soap*, ns1__Products *, const char*, const char*);

#define soap_new_ns1__Products(soap, n) soap_instantiate_ns1__Products(soap, n, NULL, NULL, NULL)


#define soap_delete_ns1__Products(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns1__Products * SOAP_FMAC2 soap_instantiate_ns1__Products(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__Products(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__integer
#define SOAP_TYPE_xsd__integer (9)
#endif

#define soap_default_xsd__integer(soap, a) soap_default_std__string(soap, a)


#define soap_serialize_xsd__integer(soap, a) soap_serialize_std__string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__integer(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_xsd__integer(struct soap*, const char*, std::string*, const char*);

#ifndef soap_write_xsd__integer
#define soap_write_xsd__integer(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "xsd:integer", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__integer(struct soap*, const std::string *, const char*, const char*);

#ifndef soap_read_xsd__integer
#define soap_read_xsd__integer(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__integer(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_xsd__integer(struct soap*, std::string *, const char*, const char*);

#define soap_new_xsd__integer(soap, n) soap_instantiate_xsd__integer(soap, n, NULL, NULL, NULL)


#define soap_delete_xsd__integer(soap, p) soap_delete(soap, p)


#define soap_instantiate_xsd__integer soap_instantiate_std__string


#define soap_copy_xsd__integer soap_copy_std__string

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);

#ifndef soap_write_std__string
#define soap_write_std__string(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "string", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);

#ifndef soap_read_std__string
#define soap_read_std__string(soap, data) ( soap_begin_recv(soap) || !soap_get_std__string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);

#define soap_new_std__string(soap, n) soap_instantiate_std__string(soap, n, NULL, NULL, NULL)


#define soap_delete_std__string(soap, p) soap_delete(soap, p)

SOAP_FMAC1 std::string * SOAP_FMAC2 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_new_SOAP_ENV__Fault(soap, n) soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Fault(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_new_SOAP_ENV__Reason(soap, n) soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Reason(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_new_SOAP_ENV__Detail(soap, n) soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Detail(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#define soap_new_SOAP_ENV__Code(soap, n) soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Code(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#define soap_new_SOAP_ENV__Header(soap, n) soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Header(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_ns1__getImagesData
#define SOAP_TYPE_ns1__getImagesData (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getImagesData(struct soap*, struct ns1__getImagesData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getImagesData(struct soap*, const struct ns1__getImagesData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getImagesData(struct soap*, const char*, int, const struct ns1__getImagesData *, const char*);
SOAP_FMAC3 struct ns1__getImagesData * SOAP_FMAC4 soap_in_ns1__getImagesData(struct soap*, const char*, struct ns1__getImagesData *, const char*);

#ifndef soap_write_ns1__getImagesData
#define soap_write_ns1__getImagesData(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__getImagesData(soap, data), 0) || soap_put_ns1__getImagesData(soap, data, "ns1:getImagesData", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getImagesData(struct soap*, const struct ns1__getImagesData *, const char*, const char*);

#ifndef soap_read_ns1__getImagesData
#define soap_read_ns1__getImagesData(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__getImagesData(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__getImagesData * SOAP_FMAC4 soap_get_ns1__getImagesData(struct soap*, struct ns1__getImagesData *, const char*, const char*);

#define soap_new_ns1__getImagesData(soap, n) soap_instantiate_ns1__getImagesData(soap, n, NULL, NULL, NULL)


#define soap_delete_ns1__getImagesData(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct ns1__getImagesData * SOAP_FMAC2 soap_instantiate_ns1__getImagesData(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getImagesData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getImagesDataResponse
#define SOAP_TYPE_ns1__getImagesDataResponse (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getImagesDataResponse(struct soap*, struct ns1__getImagesDataResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getImagesDataResponse(struct soap*, const struct ns1__getImagesDataResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getImagesDataResponse(struct soap*, const char*, int, const struct ns1__getImagesDataResponse *, const char*);
SOAP_FMAC3 struct ns1__getImagesDataResponse * SOAP_FMAC4 soap_in_ns1__getImagesDataResponse(struct soap*, const char*, struct ns1__getImagesDataResponse *, const char*);

#ifndef soap_write_ns1__getImagesDataResponse
#define soap_write_ns1__getImagesDataResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__getImagesDataResponse(soap, data), 0) || soap_put_ns1__getImagesDataResponse(soap, data, "ns1:getImagesDataResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getImagesDataResponse(struct soap*, const struct ns1__getImagesDataResponse *, const char*, const char*);

#ifndef soap_read_ns1__getImagesDataResponse
#define soap_read_ns1__getImagesDataResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__getImagesDataResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__getImagesDataResponse * SOAP_FMAC4 soap_get_ns1__getImagesDataResponse(struct soap*, struct ns1__getImagesDataResponse *, const char*, const char*);

#define soap_new_ns1__getImagesDataResponse(soap, n) soap_instantiate_ns1__getImagesDataResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_ns1__getImagesDataResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct ns1__getImagesDataResponse * SOAP_FMAC2 soap_instantiate_ns1__getImagesDataResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getImagesDataResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getProduct
#define SOAP_TYPE_ns1__getProduct (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getProduct(struct soap*, struct ns1__getProduct *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getProduct(struct soap*, const struct ns1__getProduct *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getProduct(struct soap*, const char*, int, const struct ns1__getProduct *, const char*);
SOAP_FMAC3 struct ns1__getProduct * SOAP_FMAC4 soap_in_ns1__getProduct(struct soap*, const char*, struct ns1__getProduct *, const char*);

#ifndef soap_write_ns1__getProduct
#define soap_write_ns1__getProduct(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__getProduct(soap, data), 0) || soap_put_ns1__getProduct(soap, data, "ns1:getProduct", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getProduct(struct soap*, const struct ns1__getProduct *, const char*, const char*);

#ifndef soap_read_ns1__getProduct
#define soap_read_ns1__getProduct(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__getProduct(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__getProduct * SOAP_FMAC4 soap_get_ns1__getProduct(struct soap*, struct ns1__getProduct *, const char*, const char*);

#define soap_new_ns1__getProduct(soap, n) soap_instantiate_ns1__getProduct(soap, n, NULL, NULL, NULL)


#define soap_delete_ns1__getProduct(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct ns1__getProduct * SOAP_FMAC2 soap_instantiate_ns1__getProduct(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getProduct(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getProductResponse
#define SOAP_TYPE_ns1__getProductResponse (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getProductResponse(struct soap*, struct ns1__getProductResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getProductResponse(struct soap*, const struct ns1__getProductResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getProductResponse(struct soap*, const char*, int, const struct ns1__getProductResponse *, const char*);
SOAP_FMAC3 struct ns1__getProductResponse * SOAP_FMAC4 soap_in_ns1__getProductResponse(struct soap*, const char*, struct ns1__getProductResponse *, const char*);

#ifndef soap_write_ns1__getProductResponse
#define soap_write_ns1__getProductResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__getProductResponse(soap, data), 0) || soap_put_ns1__getProductResponse(soap, data, "ns1:getProductResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getProductResponse(struct soap*, const struct ns1__getProductResponse *, const char*, const char*);

#ifndef soap_read_ns1__getProductResponse
#define soap_read_ns1__getProductResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__getProductResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__getProductResponse * SOAP_FMAC4 soap_get_ns1__getProductResponse(struct soap*, struct ns1__getProductResponse *, const char*, const char*);

#define soap_new_ns1__getProductResponse(soap, n) soap_instantiate_ns1__getProductResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_ns1__getProductResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct ns1__getProductResponse * SOAP_FMAC2 soap_instantiate_ns1__getProductResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getProductResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerToProductImagesArray
#define SOAP_TYPE_PointerToProductImagesArray (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToProductImagesArray(struct soap*, ProductImagesArray *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToProductImagesArray(struct soap*, const char *, int, ProductImagesArray *const*, const char *);
SOAP_FMAC3 ProductImagesArray ** SOAP_FMAC4 soap_in_PointerToProductImagesArray(struct soap*, const char*, ProductImagesArray **, const char*);

#ifndef soap_write_PointerToProductImagesArray
#define soap_write_PointerToProductImagesArray(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToProductImagesArray(soap, data), 0) || soap_put_PointerToProductImagesArray(soap, data, "SOAP-ENC:Array", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToProductImagesArray(struct soap*, ProductImagesArray *const*, const char*, const char*);

#ifndef soap_read_PointerToProductImagesArray
#define soap_read_PointerToProductImagesArray(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToProductImagesArray(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ProductImagesArray ** SOAP_FMAC4 soap_get_PointerToProductImagesArray(struct soap*, ProductImagesArray **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__Products
#define SOAP_TYPE_PointerTons1__Products (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__Products(struct soap*, ns1__Products *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__Products(struct soap*, const char *, int, ns1__Products *const*, const char *);
SOAP_FMAC3 ns1__Products ** SOAP_FMAC4 soap_in_PointerTons1__Products(struct soap*, const char*, ns1__Products **, const char*);

#ifndef soap_write_PointerTons1__Products
#define soap_write_PointerTons1__Products(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__Products(soap, data), 0) || soap_put_PointerTons1__Products(soap, data, "ns1:Products", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__Products(struct soap*, ns1__Products *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__Products
#define soap_read_PointerTons1__Products(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__Products(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns1__Products ** SOAP_FMAC4 soap_get_PointerTons1__Products(struct soap*, ns1__Products **, const char*, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons1__ProductImages
#define SOAP_TYPE_PointerToPointerTons1__ProductImages (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons1__ProductImages(struct soap*, ns1__ProductImages **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons1__ProductImages(struct soap*, const char *, int, ns1__ProductImages **const*, const char *);
SOAP_FMAC3 ns1__ProductImages *** SOAP_FMAC4 soap_in_PointerToPointerTons1__ProductImages(struct soap*, const char*, ns1__ProductImages ***, const char*);

#ifndef soap_write_PointerToPointerTons1__ProductImages
#define soap_write_PointerToPointerTons1__ProductImages(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToPointerTons1__ProductImages(soap, data), 0) || soap_put_PointerToPointerTons1__ProductImages(soap, data, "ns1:ProductImages", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons1__ProductImages(struct soap*, ns1__ProductImages **const*, const char*, const char*);

#ifndef soap_read_PointerToPointerTons1__ProductImages
#define soap_read_PointerToPointerTons1__ProductImages(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToPointerTons1__ProductImages(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns1__ProductImages *** SOAP_FMAC4 soap_get_PointerToPointerTons1__ProductImages(struct soap*, ns1__ProductImages ***, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__ProductImages
#define SOAP_TYPE_PointerTons1__ProductImages (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ProductImages(struct soap*, ns1__ProductImages *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ProductImages(struct soap*, const char *, int, ns1__ProductImages *const*, const char *);
SOAP_FMAC3 ns1__ProductImages ** SOAP_FMAC4 soap_in_PointerTons1__ProductImages(struct soap*, const char*, ns1__ProductImages **, const char*);

#ifndef soap_write_PointerTons1__ProductImages
#define soap_write_PointerTons1__ProductImages(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__ProductImages(soap, data), 0) || soap_put_PointerTons1__ProductImages(soap, data, "ns1:ProductImages", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ProductImages(struct soap*, ns1__ProductImages *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__ProductImages
#define soap_read_PointerTons1__ProductImages(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__ProductImages(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns1__ProductImages ** SOAP_FMAC4 soap_get_PointerTons1__ProductImages(struct soap*, ns1__ProductImages **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#endif

/* End of soapH.h */
