/* soapProductsControllerBindingProxy.h
   Generated by gSOAP 2.8.8 from Products.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapProductsControllerBindingProxy_H
#define soapProductsControllerBindingProxy_H
#include "soapH.h"

class SOAP_CMAC ProductsControllerBindingProxy : public soap
{ public:
	/// Endpoint URL of service 'ProductsControllerBindingProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	ProductsControllerBindingProxy();
	/// Construct from another engine state
	ProductsControllerBindingProxy(const struct soap&);
	/// Constructor with endpoint URL
	ProductsControllerBindingProxy(const char *url);
	/// Constructor with engine input+output mode control
	ProductsControllerBindingProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	ProductsControllerBindingProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	ProductsControllerBindingProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~ProductsControllerBindingProxy();
	/// Initializer used by constructors
	virtual	void ProductsControllerBindingProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'getProduct' (returns error code or SOAP_OK)
	virtual	int getProduct(int companyID, std::string userMD5, std::string product, struct ns1__getProductResponse &_param_1) { return getProduct(NULL, NULL, companyID, userMD5, product, _param_1); }
	virtual	int getProduct(const char *endpoint, const char *soap_action, int companyID, std::string userMD5, std::string product, struct ns1__getProductResponse &_param_1);

	/// Web service operation 'getImagesData' (returns error code or SOAP_OK)
	virtual	int getImagesData(int companyID, std::string userMD5, std::string product, struct ns1__getImagesDataResponse &_param_2) { return getImagesData(NULL, NULL, companyID, userMD5, product, _param_2); }
	virtual	int getImagesData(const char *endpoint, const char *soap_action, int companyID, std::string userMD5, std::string product, struct ns1__getImagesDataResponse &_param_2);
};
#endif
